### ISSUE TITLE
[Feature Request] Provide async ducks

### ISSUE THREAD

**Issue by GregOnNet** [mhoyer/redux-typed-ducks#3]
Hey,

I really appreciate the concept using ducks.
Currently it is a bit hard to use them through the whole project, because they don't integrate well with asynchronuous actions (e.g. Epics or Sagas).

I read about [redux-define](https://github.com/smeijer/redux-define). It proposes a way how a asyncronuous flow can be designed in redux.

Can we think of creating a kind of async duck?

```
// e.g
createMigratoryDuck('CREATE_TODO', ['SUCCESS', 'ERROR'])
```

Thanks in advance
Greg

**Comment by mhoyer** [comment]
Hi Gregor,

I am not 100% sure if I get your idea. [redux-define](https://github.com/smeijer/redux-define) really is just about generating object literals that map to strings for the action types. E.g. 

    const action = defineAction('CREATE_TODO', ['ERROR', 'SUCCESS']);

Will somehow create you an object like this one:
```
action = {
    toString = () => 'CREATE_TODO',
    ACTION = 'CREATE_TODO',
    ERROR = 'CREATE_TODO_ERROR',
    SUCCESS = 'CREATE_TODO_SUCCESS',
}
```

Not very much more if I read [defineAction.js](https://github.com/smeijer/redux-define/blob/master/src/defineAction.js) correctly.

Thus, your statement *"It proposes a way how a asyncronuous flow can be designed in redux."* is a bit confusing. 😸

The thing is, redux-ducks are actually about to bring `action types` and `reducers` together. That's the one and only purpose IMHO.

**But**, there is [redux-saga](https://redux-saga.js.org/) which I am currently checking out. So let's see if and how this can play well with my redux-typed-ducks. Stay tuned.

**Comment by mhoyer** [comment]
Regarding a **typed** redux-define this can be a starter:
```
type objectLiteral = { [key: string]: string };

function defineTypedActions<T extends objectLiteral>(type: string, subActions: T) : T & { ACTION: string } {
    const subActionKeys = Object.keys(subActions);
    const result = subActionKeys.reduce((acc, key) => {
        // creating the actual string value for the subaction property
        acc[key] = `${type}_${key}`;
        return acc;
    }, {
        ACTION: type
    });

    result.toString = () => type;
    return result as any; // trust me it will be of type T ;-)
}

// Demo time...
const action = defineTypedActions('CREATE_TODO', {
    ERROR: '',    // << nasty
    SUCCESS: '',  // << nasty
});

console.log(`${action}`);
console.log(action.ACTION);
console.log(action.ERROR);
console.log(action.SUCCESS);
```
Try it at [Typescript Playground](http://www.typescriptlang.org/play/index.html). Only nasty thing is that sub actions object literal that has to be passed into `defineTypedActions()` with empty-string properties. But its working. 👍

**Comment by mhoyer** [comment]
Even better approach IMHO. I didn't like this magic `ACTION` property of redux-define:
```
type objectLiteral = { [key: string]: string };

function defineTypedActions<T extends objectLiteral>(type: string, subActions: T): T & Function {
    const subActionKeys = Object.keys(subActions);
    const result = () => type;
    result.toString = () => type;
    subActionKeys.map(key => {
        // creating the actual string value for the subaction property
        result[key] = `${type}_${key}`;
    });

    return result as any; // trust me it will be of type T ;-)
}

// Demo time...
const action = defineTypedActions('CREATE_TODO', {
    ERROR: '',    // << nasty
    SUCCESS: '',  // << nasty
});

console.log(`${action}`); // implicitly calls .toString()
console.log(action());
console.log(action.ERROR);
console.log(action.SUCCESS);
```

**Comment by mhoyer** [comment]
@GregOnNet, I prepared a concrete sample for you. See: https://github.com/mhoyer/rtd-sagas

I hope it somehow covers your needs already. If not, let's use this example repo as a basis for further discussion.

**Comment by GregOnNet** [comment]
Hi, did not notice I haven't responded.
Thanks for the answer.

I close this issue since it is out of scope for this library.
