### ISSUE TITLE
[Discussion] Global State vs State Slice

### ISSUE THREAD

**Issue by GregOnNet** [mhoyer/redux-typed-ducks#4]
Hey,

I recognized that the global application state is passed to each reducer function.
Projects like [ngrx ](https://github.com/ngrx/platform )or [ angular-redux](https://github.com/angular-redux/store) just pass the corresponding slice of data to the reducer.

I see use cases for both approaches.

On the one hand passing the global state makes it easer to access related data slices of the store.
But on the other hand passing just a slice of the app state makes it easiear to acess the data of the current state.

We may can do some investigation whether there is a recommended way or not.
Another possibility could be letting the developer decide which mode fits better for her or his use case.

Kinds
Greg

**Comment by mhoyer** [comment]
@GregOnNet please check out the new [`createScopedReducers()`](https://github.com/mhoyer/redux-typed-ducks#createscopedreducersscopedducks-scopedinitialstates) function. I hope it solves your issue with the need of these scoped reducers map in `@ngrx/store`.
